Hm, starts to look like pcre2test is tickling MSVC2022 compiler (or rather: preprocessor) internal errors, e.g.:
    src\pcre2test.c(5207,5): warning C4013: 'pcre2_code_free_88' undefined; assuming extern returning int

which smells a heck of a lot like a preprocessor gone haywire as that '88' expansion is impossible.

Yup. propably has to do with early resolution of macros as these errors show up:

1>Z:\lib\tooling\qiqqa\MuPDF\scripts\pcre\pcre2.h(960,1): error C2011: 'pcre2_callout_enumerate_block_8': 'struct' type redefinition
1>Z:\lib\tooling\qiqqa\MuPDF\scripts\pcre\pcre2.h(960,1): error C2011: 'pcre2_substitute_callout_block_8': 'struct' type redefinition
1>Z:\lib\tooling\qiqqa\MuPDF\scripts\pcre\pcre2.h(964,1): error C2011: 'pcre2_callout_block_8': 'struct' type redefinition
1>Z:\lib\tooling\qiqqa\MuPDF\scripts\pcre\pcre2.h(964,1): error C2011: 'pcre2_callout_enumerate_block_8': 'struct' type redefinition
1>Z:\lib\tooling\qiqqa\MuPDF\scripts\pcre\pcre2.h(964,1): error C2011: 'pcre2_substitute_callout_block_8': 'struct' type redefinition

in the *second* section of the code chunk below, i.e. where PCRE clearly expects the previously defined pcre2_callout_block ( --> PCRE2_SUFFIX(pcre2_callout_block_) ) *should* be expanded only once the instantiation is a fact in that first, second and third PCRE2_TYPES_STRUCTURES_AND_FUNCTIONS line. Granted, it's not how I would've written this, but the most curious fact is that this is inside pcre2.h, which is included by everybody, but only results in these barfed hairballs when it's done in pcre2test.c VIA the amalgamation source files pcre2test_8.c et al. (We need those as otherwise the pcre2test would set unit width to zero and do its non-amalgamated thing that's not gonna fly in the 8+16+32-bit PCRE2 monolith. *Dang!* Here's the code chunk:

```
#define PCRE2_LOCAL_WIDTH 8
PCRE2_TYPES_STRUCTURES_AND_FUNCTIONS
#undef PCRE2_LOCAL_WIDTH

#define PCRE2_LOCAL_WIDTH 16
PCRE2_TYPES_STRUCTURES_AND_FUNCTIONS
#undef PCRE2_LOCAL_WIDTH

#define PCRE2_LOCAL_WIDTH 32
PCRE2_TYPES_STRUCTURES_AND_FUNCTIONS
#undef PCRE2_LOCAL_WIDTH
```